language: shell
os: linux
dist: bionic

services:
  - xvfb # for tests / examples that involve an XCB surface

env:
  global:
    - ZIG_DIR=$HOME/zig
  jobs:
    - ZIG_VERSION=0.6.0
    - ZIG_VERSION=0.7.0
    - ZIG_VERSION=0.7.1
    - ZIG_VERSION=0.8.0-dev.1032+8098b3f84

jobs:
  fast_finish: true
  allow_failures:
    - env: ZIG_VERSION=0.6.0
    - env: ZIG_VERSION=0.7.0
    - env: ZIG_VERSION=0.7.1

before_install:
  - ./travis_before_install.sh
  - export PATH=$PATH:$ZIG_DIR

addons:
  apt:
    update: true
    packages:
    - libcairo2-dev

before_script:
  - echo "Run tests with Zig compiler $(zig version)"

script:
  - zig build test
  - zig build arc
  - xvfb-run --server-args="-screen 0 1024x768x24" zig build surface_xcb
  - zig build surface_pdf