language: shell
os: linux
dist: bionic

env:
  global:
    - ZIG_DIR=$HOME/zig
  jobs:
    - ZIG_VERSION=0.6.0
    - ZIG_VERSION=0.7.0
    - ZIG_VERSION=0.7.1
    - ZIG_VERSION=0.8.0-dev.1032+8098b3f84

before_install:
  - ./travis_before_install.sh
  - export PATH=$PATH:$ZIG_DIR

addons:
  apt:
    update: true

before_script:
  - zig zen

script:
  - zig build test