language: shell
jobs:
  include:
    - os: linux
      dist: bionic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libcairo2-dev; fi
  - wget https://ziglang.org/download/0.7.1/zig-linux-x86_64-0.7.1.tar.xz
  - tar -xvf zig-linux-x86_64-0.7.1.tar.xz
  - export PATH=$PATH:$PWD/zig-linux-x86_64-0.7.1/
  - echo "Zig version $(zig version)"
  - echo "Install ziget"
  - wget https://github.com/marler8997/ziget/archive/master.zip -O /tmp/ziget-master.zip
  - unzip /tmp/ziget-master.zip -d /tmp/
  - mv /tmp/ziget-master /tmp/ziget
  - pushd /tmp/ziget && zig build && popd
  - mv /tmp/ziget/zig-cache/bin/ziget $HOME/bin
  - echo "OpenSSL version $(openssl version)"
  - echo "Install zigup"
  - wget https://github.com/marler8997/zigup/archive/master.zip -O /tmp/zigup-master.zip
  - unzip /tmp/zigup-master.zip -d /tmp/
  - mv /tmp/zigup-master /tmp/zigup
  - pushd /tmp/zigup && zig build && popd
  - mv /tmp/zigup/zig-cache/bin/zigup $HOME/bin
  - echo "Install several zig versions"
  - zigup fetch 0.6.0
  - zigup fetch 0.8.0-dev.1032+8098b3f84

addons:
  apt:
    update: true

before_script:
  - zigup list

script:
  - zigup default 0.6.0
  - zig build test
  - zigup default 0.7.1
  - zig build test
  - zig default 0.8.0-dev.1032+8098b3f84
  - zig build test