language: minimal
jobs:
  include:
    - os: linux
      dist: bionic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libcairo2-dev; fi
  - wget https://ziglang.org/download/0.7.1/zig-linux-x86_64-0.7.1.tar.xz
  - tar -xvf zig-linux-x86_64-0.7.1.tar.xz
  - export PATH=$PATH:$PWD/zig-linux-x86_64-0.7.1/
  - zig version
  - wget https://github.com/marler8997/ziget/archive/master.zip
  - unzip ziget-master.zip
  - pushd ziget-master && zig build && popd
  - export PATH=$PATH:$PWD/zig-cache/bin/
  - wget https://github.com/marler8997/zigup/archive/master.zip
  - unzip zigup-master.zip
  - pushd zigup-master && zig build && popd
  - export PATH=$PATH:$PWD/zig-cache/bin/

addons:
  apt:
    update: true

before_script:
  - echo "Zig compiler version (zig) $(zig version)"
  - echo "Zig compiler version (zigup) $(zigup default)"

script:
  - zig build test
