language: shell
jobs:
  include:
    - os: linux
      dist: bionic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libcairo2-dev; fi
  - wget https://ziglang.org/download/0.7.1/zig-linux-x86_64-0.7.1.tar.xz
  - tar -xvf zig-linux-x86_64-0.7.1.tar.xz
  - cp $PWD/zig-linux-x86_64-0.7.1/zig $HOME/bin

addons:
  apt:
    update: true

before_script:
  - zig zen

script:
  - echo "Perform tests with zig version $(zig version)"
  - zig build test
